# Site settings
title: JazzPianoTV
email: amyvpellegrini@gmail.com
description: Learn to play the Piano for real.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jazzpiano.tv" # the base hostname & protocol for your site
twitter_username: amyvpellegrini
github_username:  amypellegrini
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
