# Site settings
title: JazzPianoTV
email: amyvpellegrini@gmail.com
description: Aprende a tocar el Piano de verdad.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jazzpiano.tv" # the base hostname & protocol for your site
localurl: "http://localhost:4000"
twitter_username: amyvpellegrini
github_username:  amypellegrini
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
